Update bin

diff --git a/bin/ef b/bin/ef
--- a/bin/ef
+++ b/bin/ef
@@ -9,6 +9,7 @@ if test "${1}"; then
         read -r answer
         if echo "${answer}" | grep -viq "^n"; then
             printf "#!/bin/bash\n\n" > "${FULL_PATH}"
+            printf "set -euo pipefail\n\n" >> "${FULL_PATH}"
             printf "if test \"\${1}\"; then\n" >> "${FULL_PATH}"
 			printf "    echo test\n" >> "${FULL_PATH}"
             printf "else\n" >> "${FULL_PATH}"
