Update bash, bin

diff --git a/bin/envify b/bin/envify
--- a/bin/envify
+++ b/bin/envify
@@ -52,6 +52,19 @@ resolve_all_params() {
     fi
 }
 
+list_available_params() {
+    if command -v keyguard > /dev/null 2>&1; then
+        keyguard list
+    else
+        local host
+        if ! host=$(find_reachable_param_host); then
+            echo "Error: param server unreachable on localhost:$PARAM_SERVER_PORT and host.docker.internal:$PARAM_SERVER_PORT" >&2
+            return 1
+        fi
+        curl -sf "http://$host:$PARAM_SERVER_PORT/_keys"
+    fi
+}
+
 export_resolved_params() {
     local line key value
     while IFS= read -r line; do
@@ -85,5 +98,9 @@ resolve_params() {
 load_global_env
 
 if [ $# -gt 0 ]; then
-    resolve_params "$@"
+    if [ "$1" = "--list" ]; then
+        list_available_params
+    else
+        resolve_params "$@"
+    fi
 fi
