Update bin

diff --git a/bin/flash_disk_image b/bin/flash_disk_image
--- a/bin/flash_disk_image
+++ b/bin/flash_disk_image
@@ -12,8 +12,14 @@ diskutil list
 
 read -p "Enter the disk identifier where the image will be written (e.g., disk2): " disk_id
 
-echo "You have selected $disk_id. This will overwrite all data on the disk."
-read -p "Are you sure you want to proceed? (y/N): " confirmation
+diskutil info "/dev/${disk_id}" &>/dev/null
+if [ $? -ne 0 ]; then
+    echo "The specified disk /dev/${disk_id} does not exist. Please check the disk identifier and try again."
+    exit 1
+fi
+
+echo "You have selected $disk_id. All volumes on this disk will be unmounted to proceed with the write operation."
+read -p "Are you sure you want to proceed? This will overwrite all data on the disk. (y/N): " confirmation
 
 if [[ "${confirmation}" != "y" && "${confirmation}" != "Y" ]]; then
     echo "Operation aborted by the user."
@@ -21,7 +27,7 @@ if [[ "${confirmation}" != "y" && "${confirmation}" != "Y" ]]; then
 fi
 
 echo "Unmounting disk /dev/${disk_id}..."
-diskutil unmountDisk /dev/${disk_id} || { echo "Failed to unmount /dev/${disk_id}. Please unmount all volumes manually and try again."; exit 1; }
+diskutil unmountDisk "/dev/${disk_id}" || { echo "Failed to unmount /dev/${disk_id}. Please unmount all volumes manually and try again."; exit 1; }
 
 DD_OUTPUT_PATH="/dev/${disk_id}"
 
