Update bin

diff --git a/bin/regextest b/bin/regextest
--- a/bin/regextest
+++ b/bin/regextest
@@ -1,10 +1,10 @@
 #!/bin/bash
 
-PATTERN="^[0-9]+.([0-9]+|x)(.[0-9]+|.x)?$"
-
-while read line; do
-    echo "${line}" | [[ "${line}" =~ ${PATTERN} ]] && echo -ne "FOUND\t\t" || echo -ne "NOT FOUND\t"
-    echo "${line}"
+if test "${1}"; then
+    PATTERN="${1}"
+    while read line; do
+        echo "${line}" | [[ "${line}" =~ ${PATTERN} ]] && echo -ne "FOUND\t\t" || echo -ne "NOT FOUND\t"
+        echo "${line}"
 done <<< "bla
 dsf.sdf
 adf.fds.fds
@@ -22,4 +22,7 @@ bugfix/bla
 2.1.x
 2.x
 22.22.x"
-
+else
+    echo "usage: `basename ${0}` <pattern>"
+    echo "example: `basename ${0}` \"^[0-9]+.([0-9]+|x)(.[0-9]+|.x)?$\""
+fi
