Update bin

diff --git a/bin/tmbackup b/bin/tmbackup
--- a/bin/tmbackup
+++ b/bin/tmbackup
@@ -5,6 +5,20 @@ if ! test "${TM_USER}"; then
     exit 1
 fi
 
-BACKUP_PATH="${WDIR}/private/infrastructure/backup/teslamate/backup"
-kubectl exec -i deployment.apps/teslamate-mazzotta-db-deployment -n teslamate-mazzotta -- /bin/sh -c "pg_dump -U ${TM_USER} -d ${TM_USER}" > "${BACKUP_PATH}/$(date +%Y-%m-%dT%H-%M-%S).sql"
+BACKUP_DIR="${WDIR}/private/infrastructure/backup/teslamate/backup"
+BACKUP_PATH="${BACKUP_DIR}/$(date +%Y-%m-%dT%H-%M-%S).sql"
+
+kubectl exec -i deployment.apps/teslamate-mazzotta-db-deployment -n teslamate-mazzotta -- /bin/sh -c "pg_dump -U ${TM_USER} -d ${TM_USER}" > "${BACKUP_PATH}"
+
+if [[ $? == 0 ]]; then
+    BACKUP_TABLE_COUNT=$(cat ${BACKUP_PATH} | grep 'COPY public.' | wc -l | sed 's/ //g')
+    if [[ "${BACKUP_TABLE_COUNT}" == "13" ]]; then
+        exit 0
+    else
+        echo "Warning! Looks like some tables haven't been backed up! Backed up tables: ${BACKUP_TABLE_COUNT}"
+        exit 1
+    fi
+else
+    echo "Backup FAILED"
+fi
 
